allowBuilds:
  browser-tabs-lock: set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@clerk/clerk-js@6.25.10'
  - '@clerk/expo@4.1.0'
